apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-admin-binding
  namespace: mongodb
subjects:
- kind: ServiceAccount
  name: mongo-admin
  namespace: mongodb
roleRef:
  kind: Role
  name: mongo-admin-role
  apiGroup: rbac.authorization.k8s.io

